spring:
  application:
    name: seata-order-application
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.33.10:8848
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.33.10:3306/seata-order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
dubbo:
  scan:
    base-packages: com.itsz
  protocol:
    name: dubbo
    port: 20882
    serialization: kryo
  registry:
    address: nacos://192.168.33.10:8848
  provider:
    loadbalance: roundrobin
server:
  port: 9002